package portal

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// ProjectType identifies which kind of Liferay project a root directory is.
// The zero value, ProjectTypeUnknown, means neither marker was found — never
// treat an unset ProjectType as a valid project.
type ProjectType int

const (
	ProjectTypeUnknown ProjectType = iota
	Monorepo
	Workspace
)

// DetectProjectType reports which kind of Liferay project dir is (checking
// dir itself, not its ancestors), or ProjectTypeUnknown when neither the
// monorepo markers (build.xml + modules/) nor a Liferay Workspace marker
// (a com.liferay.workspace Gradle plugin application) are present.
func DetectProjectType(dir string) ProjectType {
	if isPortalRoot(dir) {
		return Monorepo
	}
	if isWorkspaceRoot(dir) {
		return Workspace
	}
	return ProjectTypeUnknown
}

// isWorkspaceRoot reports whether dir is the root of a Liferay Workspace — a
// project built with the com.liferay.workspace Gradle plugin (e.g. one
// generated by "blade init"), identified by the plugin application in
// settings.gradle or build.gradle.
func isWorkspaceRoot(dir string) bool {
	for _, name := range []string{"settings.gradle", "build.gradle"} {
		content, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			continue
		}
		s := string(content)
		if strings.Contains(s, `"com.liferay.workspace"`) || strings.Contains(s, `'com.liferay.workspace'`) {
			return true
		}
	}
	return false
}

// ErrNotInPortal is the sentinel wrapped by FindRoot's failure so callers can
// distinguish "not inside a portal" from other errors via errors.Is, without
// depending on message text.
var ErrNotInPortal = errors.New("not inside a liferay-portal repository or Liferay Workspace (build.xml + modules/, or a workspace-plugin build.gradle/settings.gradle, not found)")

// FindRoot walks up from dir looking for a Liferay project root — either a
// monorepo root (build.xml + modules/) or a Liferay Workspace root (a
// com.liferay.workspace Gradle plugin application).
func FindRoot(dir string) (string, error) {
	d := dir
	for {
		if DetectProjectType(d) != ProjectTypeUnknown {
			return d, nil
		}
		parent := filepath.Dir(d)
		if parent == d {
			return "", ErrNotInPortal
		}
		d = parent
	}
}

// IsPortalRepo returns true when dir looks like a liferay-portal root.
func IsPortalRepo(dir string) bool {
	return isPortalRoot(dir)
}

// BundleDir returns the resolved bundle directory for the given root,
// honouring app.server.properties / app.server.<user>.properties overrides
// for a Monorepo root, or liferay.workspace.home.dir (default "bundles") in
// gradle.properties for a Workspace root.
func BundleDir(portalRoot string) (string, error) {
	if DetectProjectType(portalRoot) == Workspace {
		return workspaceBundleDir(portalRoot)
	}

	props := readAppServerProps(portalRoot)

	dir := props["app.server.parent.dir"]
	if dir == "" {
		dir = filepath.Join(filepath.Dir(portalRoot), "bundles")
	} else {
		dir = resolveProperty(dir, portalRoot, props)
	}
	return filepath.Clean(dir), nil
}

func workspaceBundleDir(portalRoot string) (string, error) {
	props, _ := ReadProperties(filepath.Join(portalRoot, "gradle.properties"))
	dir := props["liferay.workspace.home.dir"]
	if dir == "" {
		dir = "bundles"
	}
	return filepath.Clean(filepath.Join(portalRoot, dir)), nil
}

// FindTomcatDir resolves the Tomcat directory. For a Monorepo root this reads
// app.server.properties (the version is always authoritative there). For a
// Workspace root, which has no such property, it globs bundleDir/tomcat-*
// and picks the numerically highest version.
func FindTomcatDir(portalRoot string) (string, error) {
	if DetectProjectType(portalRoot) == Workspace {
		return workspaceTomcatDir(portalRoot)
	}

	props := readAppServerProps(portalRoot)

	dir := props["app.server.tomcat.dir"]
	if dir == "" {
		version := props["app.server.tomcat.version"]
		if version == "" {
			return "", fmt.Errorf("app.server.tomcat.version not set in %s/app.server.properties", portalRoot)
		}
		bundleDir, err := BundleDir(portalRoot)
		if err != nil {
			return "", err
		}
		return filepath.Join(bundleDir, "tomcat-"+version), nil
	}

	return filepath.Clean(resolveProperty(dir, portalRoot, props)), nil
}

func workspaceTomcatDir(portalRoot string) (string, error) {
	bundleDir, err := BundleDir(portalRoot)
	if err != nil {
		return "", err
	}
	matches, err := filepath.Glob(filepath.Join(bundleDir, "tomcat-*"))
	if err != nil {
		return "", err
	}
	if len(matches) > 0 {
		return highestVersionDir(matches), nil
	}

	// Some workspace plugin versions name the directory just "tomcat",
	// with no version suffix.
	plainDir := filepath.Join(bundleDir, "tomcat")
	if dirExists(plainDir) {
		return plainDir, nil
	}

	return "", fmt.Errorf("no tomcat-* or tomcat directory found under %s — run \"liferay build\" to assemble the bundle first", bundleDir)
}

// highestVersionDir returns the entry from a set of ".../tomcat-X.Y.Z" paths
// with the numerically highest version, comparing dot-separated segments as
// integers so "tomcat-10.1.15" correctly beats "tomcat-9.0.99".
func highestVersionDir(paths []string) string {
	best := paths[0]
	for _, p := range paths[1:] {
		if compareVersions(tomcatVersion(best), tomcatVersion(p)) < 0 {
			best = p
		}
	}
	return best
}

func tomcatVersion(path string) string {
	return strings.TrimPrefix(filepath.Base(path), "tomcat-")
}

func compareVersions(a, b string) int {
	as := strings.Split(a, ".")
	bs := strings.Split(b, ".")
	for i := 0; i < len(as) || i < len(bs); i++ {
		var av, bv int
		if i < len(as) {
			av, _ = strconv.Atoi(as[i])
		}
		if i < len(bs) {
			bv, _ = strconv.Atoi(bs[i])
		}
		if av != bv {
			return av - bv
		}
	}
	return 0
}

func readAppServerProps(portalRoot string) map[string]string {
	props, err := ReadProperties(filepath.Join(portalRoot, "app.server.properties"))
	if err != nil {
		props = map[string]string{}
	}

	if username, err := SafeUsername(); err == nil {
		override := filepath.Join(portalRoot, "app.server."+username+".properties")
		if overrideProps, err := ReadProperties(override); err == nil {
			for k, v := range overrideProps {
				props[k] = v
			}
		}
	}
	return props
}

func resolveProperty(value, portalRoot string, props map[string]string) string {
	props["project.dir"] = portalRoot
	for i := 0; i < 10 && strings.Contains(value, "${"); i++ {
		prev := value
		for k, v := range props {
			value = strings.ReplaceAll(value, "${"+k+"}", v)
		}
		if value == prev {
			break
		}
	}
	return value
}

func isPortalRoot(dir string) bool {
	return fileExists(filepath.Join(dir, "build.xml")) && dirExists(filepath.Join(dir, "modules"))
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func dirExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}
