package cli

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"

	"github.com/david-truong/liferay-portal-cli/internal/portal"
)

// autofixWorktree writes per-worktree config files that the CLI expects but
// that weren't generated by `liferay worktree add` (e.g., for worktrees made
// via plain `git worktree add`). Idempotent; only acts in linked worktrees.
func autofixWorktree(portalRoot string) {
	info, err := os.Stat(filepath.Join(portalRoot, ".git"))
	if err != nil || info.IsDir() {
		return
	}

	u, err := user.Current()
	if err != nil {
		return
	}

	appServerName := fmt.Sprintf("app.server.%s.properties", u.Username)
	appServerPath := filepath.Join(portalRoot, appServerName)
	if _, err := os.Stat(appServerPath); os.IsNotExist(err) {
		content := "app.server.parent.dir=${project.dir}/bundles\n"
		if err := os.WriteFile(appServerPath, []byte(content), 0644); err == nil {
			fmt.Fprintf(os.Stderr, "[liferay] auto-fixed worktree: wrote %s\n", appServerName)
		}
	}

	bundleDir, err := portal.BundleDir(portalRoot)
	if err != nil {
		return
	}
	wizPath := filepath.Join(bundleDir, "portal-setup-wizard.properties")
	if _, err := os.Stat(wizPath); !os.IsNotExist(err) {
		return
	}
	if err := os.MkdirAll(filepath.Dir(wizPath), 0755); err != nil {
		return
	}
	content := "admin.email.from.address=test@liferay.com\n" +
		"admin.email.from.name=Test Test\n" +
		"company.default.locale=en_US\n" +
		"company.default.time.zone=UTC\n" +
		"company.default.web.id=liferay.com\n" +
		"default.admin.email.address.prefix=test\n" +
		"liferay.home=" + bundleDir + "\n" +
		"setup.wizard.enabled=false\n"
	if err := os.WriteFile(wizPath, []byte(content), 0644); err == nil {
		rel, relErr := filepath.Rel(portalRoot, wizPath)
		if relErr != nil {
			rel = wizPath
		}
		fmt.Fprintf(os.Stderr, "[liferay] auto-fixed worktree: wrote %s\n", rel)
	}
}
