package docker

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
)

const composeTemplate = `services:
  db:
    image: mysql:8.0
    command:
      - --general-log=1
      - --general-log-file=/var/log/mysql/mysql.log
      - --slow-query-log=1
      - --slow-query-log-file=/var/log/mysql/slow.log
      - --lower-case-table-names=1
      - --innodb-buffer-pool-size=1G
      - --innodb_flush_log_at_trx_commit=0
      - --innodb-redo-log-capacity=1G
      - --net-buffer-length=1000000
      - --max-allowed-packet=1000000000
      - --skip-log-bin
    volumes:
      - ./db/log:/var/log/mysql
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lportal
    ports:
      - "{{.Ports.MySQL}}:3306"
    expose:
      - 3306

  tomcat:
    image: eclipse-temurin:21-jdk
    working_dir: /opt/liferay
    volumes:
      - {{.BundleDir}}:/opt/liferay
      - {{.PortalExtOverride}}:/opt/liferay/portal-ext.properties
    entrypoint: ["sh", "-c", "{{.TomcatDir}}/bin/catalina.sh run"]
    environment:
      CATALINA_OPTS: >-
        -Dfile.encoding=UTF-8
        -Djava.net.preferIPv4Stack=true
        -Duser.timezone=GMT
        -XX:MaxMetaspaceSize=768m
        -XX:MaxNewSize=1536m
        -XX:MetaspaceSize=768m
        -XX:NewSize=1536m
        -XX:SurvivorRatio=7
        -Xms2560m
        -Xmx2560m
        --add-opens=java.base/java.lang=ALL-UNNAMED
        --add-opens=java.base/java.lang.invoke=ALL-UNNAMED
        --add-opens=java.base/java.lang.reflect=ALL-UNNAMED
        --add-opens=java.base/java.net=ALL-UNNAMED
        --add-opens=java.base/sun.net.www.protocol.http=ALL-UNNAMED
        --add-opens=java.base/sun.net.www.protocol.https=ALL-UNNAMED
        --add-opens=java.base/sun.util.calendar=ALL-UNNAMED
        --add-opens=jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
    ports:
      - "{{.Ports.Tomcat}}:8080"
      - "{{.Ports.Debug}}:8000"
      - "{{.Ports.Gogo}}:13331"
    depends_on:
      - db

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "{{.Ports.Adminer}}:8080"
`

const portalExtOverrideTemplate = `# Generated by liferay-cli server up. Do not edit — regenerated on each up.
# Overrides jdbc.default.* so the Tomcat container connects to the compose db service.
jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.default.url=jdbc:mysql://db:3306/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true&databaseTerm=CATALOG
jdbc.default.username=root
jdbc.default.password=root
module.framework.properties.osgi.console=0.0.0.0:13331
`

type composeParams struct {
	BundleDir         string
	TomcatDir         string
	PortalExtOverride string
	Ports             Ports
}

type portsJSON struct {
	Slot int `json:"slot"`
}

// StateDir returns the path to the per-worktree CLI state directory.
func StateDir(worktreeRoot string) string {
	return filepath.Join(worktreeRoot, ".liferay-cli", "docker")
}

// Setup generates docker-compose.yml and portal-ext override in the state dir.
// Returns the Ports in use.
func Setup(worktreeRoot, bundleDir, tomcatDirName string) (Ports, error) {
	stateDir := StateDir(worktreeRoot)
	if err := os.MkdirAll(filepath.Join(stateDir, "db", "log"), 0755); err != nil {
		return Ports{}, err
	}

	ports, err := loadOrAllocatePorts(stateDir, worktreeRoot)
	if err != nil {
		return Ports{}, err
	}

	overridePath := filepath.Join(stateDir, "portal-ext.properties")
	if err := os.WriteFile(overridePath, []byte(portalExtOverrideTemplate), 0644); err != nil {
		return Ports{}, fmt.Errorf("writing portal-ext override: %w", err)
	}

	params := composeParams{
		BundleDir:         toUnixPath(bundleDir),
		TomcatDir:         tomcatDirName,
		PortalExtOverride: toUnixPath(overridePath),
		Ports:             ports,
	}

	tmpl, err := template.New("compose").Parse(composeTemplate)
	if err != nil {
		return Ports{}, fmt.Errorf("parsing compose template: %w", err)
	}

	composePath := filepath.Join(stateDir, "docker-compose.yml")
	f, err := os.Create(composePath)
	if err != nil {
		return Ports{}, fmt.Errorf("creating docker-compose.yml: %w", err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, params); err != nil {
		return Ports{}, fmt.Errorf("rendering compose template: %w", err)
	}

	return ports, nil
}

// ComposePath returns the path to the generated docker-compose.yml.
func ComposePath(worktreeRoot string) string {
	return filepath.Join(StateDir(worktreeRoot), "docker-compose.yml")
}

// Run executes `docker compose -f <compose-file> <args...>` streaming output.
func Run(worktreeRoot string, args ...string) error {
	if err := checkDocker(); err != nil {
		return err
	}
	composePath := ComposePath(worktreeRoot)
	cmdArgs := append([]string{"compose", "-f", composePath}, args...)
	cmd := exec.Command("docker", cmdArgs...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	return cmd.Run()
}

func loadOrAllocatePorts(stateDir, worktreeRoot string) (Ports, error) {
	portsFile := filepath.Join(stateDir, "ports.json")
	if data, err := os.ReadFile(portsFile); err == nil {
		var pj portsJSON
		if json.Unmarshal(data, &pj) == nil && pj.Slot >= 0 {
			return PortsFromSlot(pj.Slot), nil
		}
	}

	ports := AllocatePorts(worktreeRoot)
	data, _ := json.Marshal(portsJSON{Slot: ports.Slot})
	os.WriteFile(portsFile, data, 0644)
	return ports, nil
}

func checkDocker() error {
	if _, err := exec.LookPath("docker"); err != nil {
		return fmt.Errorf(
			"docker not found on PATH\n\n" +
				"Install Docker:\n" +
				"  macOS/Windows: https://www.docker.com/products/docker-desktop\n" +
				"  Linux: https://docs.docker.com/engine/install/")
	}
	cmd := exec.Command("docker", "info")
	cmd.Stdout = nil
	cmd.Stderr = nil
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("docker is not running — start Docker Desktop (or the Docker daemon) and try again")
	}
	return nil
}

// toUnixPath converts a filepath to forward slashes (needed in docker-compose.yml on all OSes).
func toUnixPath(p string) string {
	return strings.ReplaceAll(p, "\\", "/")
}
