package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/david-truong/liferay-portal-cli/internal/docker"
	"github.com/david-truong/liferay-portal-cli/internal/gradle"
	"github.com/david-truong/liferay-portal-cli/internal/portal"
	"github.com/spf13/cobra"
)

var testIntegrationTests string

var testIntegrationCmd = &cobra.Command{
	Use:   "test-integration <module>",
	Short: "Run integration tests for a Liferay module",
	Long: `Resolves the module by name and runs "gw testIntegration --tests <filter>" in its directory.

--tests accepts any pattern supported by Gradle's Test task.

A host-native Liferay server must be running — the Arquillian junit-bridge and
DataGuard connectors both use loopback sockets, so the server and the Gradle
test JVM must share the host's 127.0.0.1.

If this worktree is on slot 0 (stock ports), the command is a straight
pass-through to "gw testIntegration". On slot > 0 a Gradle init script is
written to .gradle/ that pins testIntegrationTomcat.portNumber to the bundle's
HTTP port and injects -Dliferay.arquillian.port / -Dliferay.data.guard.port
into the test JVM so the client matches the OSGi-configured server ports.

All invocations work from the portal root — no cd required.

Examples:
  liferay test-integration change-tracking-web --tests "*FooTest"
  liferay test-integration change-tracking-web --tests "com.liferay.foo.FooTest"`,
	Args: cobra.ExactArgs(1),
	RunE: runTestIntegration,
}

func init() {
	testIntegrationCmd.Flags().StringVar(&testIntegrationTests, "tests", "", "Gradle test filter (class name, wildcard, or class.method)")
	testIntegrationCmd.MarkFlagRequired("tests")
	rootCmd.AddCommand(testIntegrationCmd)
}

func runTestIntegration(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}

	portalRoot, err := portal.FindRoot(cwd)
	if err != nil {
		return err
	}

	idx, err := portal.BuildModuleIndex(portalRoot)
	if err != nil {
		return fmt.Errorf("building module index: %w", err)
	}

	modulePath, err := idx.Resolve(args[0])
	if err != nil {
		return err
	}

	gwArgs := []string{"testIntegration", "--tests", testIntegrationTests}

	if initScript, err := writeSlotInitScript(portalRoot); err != nil {
		return err
	} else if initScript != "" {
		gwArgs = append([]string{"-I", initScript}, gwArgs...)
	}

	gwCmd, err := gradle.Command(modulePath, gwArgs...)
	if err != nil {
		return err
	}
	gwCmd.Stdout = os.Stdout
	gwCmd.Stderr = os.Stderr
	gwCmd.Stdin = os.Stdin
	return gwCmd.Run()
}

// writeSlotInitScript writes .gradle/liferay-test-integration-init.gradle if
// the worktree has a non-stock slot assigned, and returns its path. For slot 0
// (or when no state exists yet) it returns "" so the caller skips the -I flag
// and behaves as a straight pass-through.
func writeSlotInitScript(portalRoot string) (string, error) {
	state, ok := docker.LoadState(portalRoot)
	if !ok {
		return "", nil
	}
	ports := docker.PortsFromSlot(state.Slot)
	if ports.IsStock() {
		return "", nil
	}

	gradleDir := filepath.Join(portalRoot, ".gradle")
	if err := os.MkdirAll(gradleDir, 0755); err != nil {
		return "", err
	}

	path := filepath.Join(gradleDir, "liferay-test-integration-init.gradle")
	content := fmt.Sprintf(`// Auto-generated by liferay-cli for worktree slot %d.
// Pins testIntegrationTomcat.portNumber to the bundle's HTTP port, and
// forwards liferay.arquillian.port / liferay.data.guard.port into the test JVM
// so the client dials the OSGi-configured server ports.
allprojects {
	afterEvaluate { project ->
		if (project.extensions.findByName('testIntegrationTomcat')) {
			project.testIntegrationTomcat.portNumber = %d
		}
		project.tasks.matching { it.name == 'testIntegration' }.all { t ->
			t.jvmArgs '-Dliferay.arquillian.port=%d', '-Dliferay.data.guard.port=%d'
		}
	}
}
`, ports.Slot, ports.TomcatHTTP, ports.Arquillian, ports.DataGuard)

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return "", err
	}
	return path, nil
}
